server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway
  cloud:
      gateway:
        routes:
          - id: products
            uri: http://localhost:8082/
            predicates:
              - Path=/api/products**
          - id: ShoppingCarts
            uri: http://localhost:8083/
            predicates:
              - Path=/api/basket**
